swipe:
  3:
    up:
      command: 'xdotool key super'
    down:
      command: 'xdotool key super'
    left:
      command: 'xdotool key ctrl+alt+Up'
    right:
      command: 'xdotool key ctrl+alt+Down'
  4:
    up:
      command: 'xdotool key super+Up'
    down:
      command: 'xdotool key super+Down'
    left:
      command: 'xdotool key super+Left'
    right:
      command: 'xdotool key super+Right'
# pinch:
  # 2:
    # in:
      # command: 'xdotool key super+Up'
    # out:
      # command: 'xdotool key super+Down'
pinch:
  in:
    command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
  out:
    command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
threshold:
  swipe: 0.3
  pinch: 0.1
interval:
  # swipe: 1
  # pinch: 1
  swipe: 0.5
  pinch: 0.5
